### ISSUE TITLE
user cannot download excel from Coordinated Entry Assessment Status report

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#68] opened 2020-03-05 14:22 UTC
PSI user Leo Adorno gets "504 Gateway Timeout" when trying to download an excel version of the "Coordinated Entry Assessment Status" report.

**Comment by cujocon1978** [comment] 2020-03-05 15:28
@margocramer do you happen to know the browser in use, or if this is repeatable for other users?

**Comment by margocramer** [comment] 2020-03-05 20:30
I masqueraded as him in Chrome this morning and encountered the same issue.

**Comment by eanders** [comment] 2020-03-07 15:49
@margocramer this should be fixed now.

**Comment by margocramer** [comment] 2020-03-09 13:55
@eanders I attempted again this morning and received the same Gateway Time-out message . Leo Adorno reported the same thing over the weekend.

**Comment by eanders** [comment] 2020-03-09 15:46
Thanks @margocramer.  We'll need to make some major adjustments to the way the report works then.  The issue is that since no one has been assessed, the list is quite large.  Is there any harm in simply including the first 500 or so in the export?

**Closed** 2020-04-10 20:19 UTC
Labels: bug
